# Generated by Django 4.1.6 on 2023-02-21 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0002_appointmentdetails_delete_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentdetails',
            name='email',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='appointmentdetails',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
