# Generated by Django 4.1.6 on 2023-02-21 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0004_remove_appointmentdetails_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentdetails',
            name='doctor',
            field=models.CharField(default=22.0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appointmentdetails',
            name='email',
            field=models.CharField(default=22.0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appointmentdetails',
            name='service',
            field=models.CharField(default=22.0, max_length=50),
            preserve_default=False,
        ),
    ]
