# Generated by Django 4.2.2 on 2023-06-17 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0005_appointmentdetails_doctor_appointmentdetails_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentdetails',
            name='date1',
            field=models.DateField(null=True),
        ),
    ]
