# Generated by Django 4.2.2 on 2023-06-17 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0006_appointmentdetails_date1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentdetails',
            name='date1',
            field=models.DateField(default=11.11),
            preserve_default=False,
        ),
    ]
